### ISSUE TITLE
Error downloading file with [] in URI

### ISSUE THREAD

**Issue by henrydavidge** [nsrr/nsrr-gem#25]
```
Traceback (most recent call last):
	20: from /Users/henrydavidge/.rbenv/versions/2.7.2/bin/nsrr:23:in `<main>'
	19: from /Users/henrydavidge/.rbenv/versions/2.7.2/bin/nsrr:23:in `load'
	18: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/bin/nsrr:6:in `<top (required)>'
	17: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr.rb:16:in `launch'
	16: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr.rb:26:in `download'
	15: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/commands/download.rb:14:in `run'
	14: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/commands/download.rb:39:in `run'
	13: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:81:in `download'
	12: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:123:in `download_helper'
	11: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:123:in `each'
	10: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:124:in `block in download_helper'
	 9: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:103:in `download_helper'
	 8: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:103:in `each'
	 7: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:111:in `block in download_helper'
	 6: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/file.rb:39:in `download'
	 5: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/file.rb:61:in `force_download'
	 4: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/models/file.rb:61:in `new'
	 3: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/nsrr-8.0.0/lib/nsrr/helpers/download_request.rb:20:in `initialize'
	 2: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	 1: from /Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
/Users/henrydavidge/.rbenv/versions/2.7.2/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://sleepdata.org/datasets/stages/files/a/12394-G3hrGmK5eHkEbq7dwc8S/m/nsrr-gem-v8-0-0/original/Project%20Descriptions/30K%20Proposal%20and%20Appendices%20Updated%202016-10-10[1].pdf" (URI::InvalidURIError)
```

This looks similar to #24, it might be a good idea to URI everything that should be interpreted as URI.

**Comment by mrueschman** [comment]
Thanks for reporting. For that particular file I removed the brackets in case this issue lingers for a bit.
