### ISSUE TITLE
TypeError in dataset.rb when using the download method with Ruby 3.0.2

### ISSUE THREAD

**Issue by Xufeng-gif** [nsrr/nsrr-gem#27]
Hello,

I'm using the NSRR gem to download datasets and I've encountered an error when using the `download` method. Here are the steps to reproduce the issue:

1. I've started the NSRR console using the command `nsrr console`.
2. In the console, I've retrieved a dataset using `d = Dataset.find "nchsdb"`.
3. I've then attempted to download this dataset using `d.download`.

At this point, I get a `TypeError` with the message `wrong argument type nil (expected Regexp)`. The stack trace points to the `download_helper` method in `dataset.rb`. Here's the full error message and stack trace:

nsrr console
Loading environment (Nsrr 8.0.0)
3.0.0 :001 > d = Dataset.find "nchsdb"
 => 
#<Dataset:0x000055a5e7403f70
... 
3.0.0 :002 > d.download
           File Check: md5
           File Regex: nil
                Depth: recursive

  Get your token here: https://sleepdata.org/token
  Your input is hidden while entering token.
     Enter your token: AUTHORIZED as  
      create nchsdb/
      create nchsdb/datasets/
/home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:104:in `match?': wrong argument type nil (expected Regexp) (TypeError)
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:104:in `block in download_helper'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:103:in `each'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:103:in `download_helper'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:124:in `block in download_helper'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:123:in `each'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:123:in `download_helper'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/models/dataset.rb:81:in `download'
	from (irb):2:in `<main>'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/commands/console.rb:26:in `start'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr/commands/console.rb:13:in `start'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr.rb:21:in `console'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/lib/nsrr.rb:16:in `launch'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/gems/nsrr-8.0.0/bin/nsrr:6:in `<top (required)>'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/bin/nsrr:23:in `load'
	from /home/xufeng/.rvm/gems/ruby-3.0.0/bin/nsrr:23:in `<main>'
3.0.0 :003 > 

4. My environment is as follows:
- Ruby version: 3.0.2
- NSRR gem version: 8.0.0
- Operating System: Ubuntu 20.04

I've tried the following to resolve the issue but without success:

    Checking the NSRR gem documentation for any known issues or required settings.
    Searching for similar issues in this repository and on StackOverflow.
    Trying to modify the argument type from Regexp to nil, but I'm unsure of how to do this.

I would appreciate any help or suggestions for how to resolve this issue. Thank you.

**Comment by mrueschman** [comment]
Thanks for reporting the issue and for providing all these details.

What happens when you run the **nsrr download nchsdb** command from your terminal? Running **nsrr download <dataset name/path>** is the typical command run by users -- it would be useful to see if you receive the same error there.

**Comment by Xufeng-gif** [comment]
Hello,

Thank you for your response.

In line with your suggestion, I tried the nsrr download nchsdb command directly from my terminal. The download did start successfully, although there were a few failures presumably due to weak weblinks.

Given this, it seems the issue is indeed specific to the nsrr console mode and not the NSRR gem overall. I appreciate your guidance on using the nsrr download command directly, which will be very helpful for my immediate needs. However, it might still be worth investigating the issue with the nsrr console mode for the benefit of other users who might prefer or need to use that mode.

Please let me know if there are any other tests you would like me to run or further information I can provide to assist with resolving the issue.

Best regards,

Xufeng













At 2023-07-03 07:15:53, "Michael Rueschman" ***@***.***> wrote:

Thanks for reporting the issue and for providing all these details.

What happens when you run the nsrr download nchsdb command from your terminal? Running nsrr download <dataset name/path> is the typical command run by users -- it would be useful to see if you receive the same error there.

**Comment by mrueschman** [comment]
Thanks - I agree with your assessment. I'm glad you were able to successfully start downloading NSRR data. We will try to take a look at the issue in the console in the future.
